openapi: 3.0.1
info:
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  description: "Use these APIs to interact with the Identity Security Cloud platform\
    \ to achieve repeatable, automated processes with greater scalability. We encourage\
    \ you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss\
    \ to connect with other developers using our APIs."
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://developer.sailpoint.com/discuss/tos
  title: Identity Security Cloud API - Public Identities
  version: v1
servers:
- description: This is the production API server.
  url: "https://{tenant}.api.identitynow.com"
  variables:
    tenant:
      default: sailpoint
      description: "This is the name of your tenant, typically your company's name."
- description: This is the versioned API server.
  url: "https://{apiUrl}"
  variables:
    apiUrl:
      default: sailpoint.api.identitynow.com
      description: This is the api url of your tenant
security:
- userAuth:
  - sp:scopes:all
tags:
- description: "Use this API in conjunction with [Public Identites Config](https://developer.sailpoint.com/docs/api/v2025/public-identities-config/)\
    \ to enable non-administrators to view identities' publicly visible attributes.\
    \ \nWith this functionality in place, non-administrators can view identity attributes\
    \ other than the default attributes (email, lifecycle state, and manager), depending\
    \ on which identity attributes their organization administrators have made public.\
    \ \nThis can be helpful for access approvers, certification reviewers, managers\
    \ viewing their direct reports' access, and source owners viewing their tasks.\n"
  name: Public Identities
paths:
  /public-identities/v1:
    get:
      description: Get a list of public identities.  Set `add-core-filters` to `true`
        to exclude incomplete identities and uncorrelated accounts.
      operationId: getPublicIdentitiesV1
      parameters:
      - description: |-
          Max number of results to return.
          See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
        example: 250
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 250
          format: int32
          maximum: 250
          minimum: 0
          type: integer
        style: form
      - description: |-
          Offset into the full result set. Usually specified with *limit* to paginate through the results.
          See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
        example: 0
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          format: int32
          minimum: 0
          type: integer
        style: form
      - description: |-
          If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.

          Since requesting a total count can have a performance impact, it is recommended not to send **count=true** if that value will not be used.

          See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
        example: true
        explode: true
        in: query
        name: count
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - description: |-
          Filter results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#filtering-results)

          Filtering is supported for the following fields and operators:

          **id**: *eq, in*

          **alias**: *eq, sw*

          **email**: *eq, sw*

          **firstname**: *eq, sw*

          **lastname**: *eq, sw*
        example: firstname eq "John"
        explode: true
        in: query
        name: filters
        required: false
        schema:
          type: string
        style: form
      - description: |-
          If *true*, only get identities which satisfy ALL the following criteria in addition to any criteria specified by *filters*:
            - Should be either correlated or protected.
            - Should not be "spadmin" or "cloudadmin".
            - uid should not be null.
            - lastname should not be null.
            - email should not be null.
        example: false
        explode: true
        in: query
        name: add-core-filters
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - description: |-
          Sort results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#sorting-results)

          Sorting is supported for the following fields: **name**
        example: name
        explode: true
        in: query
        name: sorters
        required: false
        schema:
          format: comma-separated
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              example:
              - id: 2c9180857182305e0171993735622948
                name: Alison Ferguso
                alias: alison.ferguso
                email: alison.ferguso@acme-solar.com
                status: Active
                manager:
                  type: IDENTITY
                  id: 2c9180a46faadee4016fb4e018c20639
                  name: Thomas Edison
                attributes:
                - key: phone
                  name: Phone
                  value: "5125551234"
                - key: country
                  name: Country
                  value: US
              - id: 2c9180a46faadee4016fb4e018c20639
                name: Thomas Edison
                alias: thomas.edison
                email: thomas.edison@acme-solar.com
                status: Active
                manager:
                  type: IDENTITY
                  id: 2c918086676d3e0601677611dbde220f
                  name: Mister Manager
                attributes:
                - key: phone
                  name: Phone
                  value: "5125554321"
                - key: country
                  name: Country
                  value: US
              schema:
                items:
                  $ref: '#/components/schemas/publicidentity'
                type: array
          description: A list of public identity objects.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Client Error - Returned if the request body is invalid.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getPublicIdentitiesV1_401_response'
          description: "Unauthorized - Returned if there is no authorization header,\
            \ or if the JWT token is expired."
        "403":
          content:
            application/json:
              examples:
                "403":
                  summary: An example of a 403 response object
                  value:
                    detailCode: 403 Forbidden
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server understood the request but refuses to authorize
                        it.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: "Forbidden - Returned if the user you are running as, doesn't\
            \ have access to this end-point."
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getPublicIdentitiesV1_429_response'
          description: Too Many Requests - Returned in response to too many requests
            in a given period of time - rate limited. The Retry-After header in the
            response includes how long to wait before trying again.
        "500":
          content:
            application/json:
              examples:
                "500":
                  summary: An example of a 500 response object
                  value:
                    detailCode: 500.0 Internal Fault
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: An internal fault occurred.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Internal Server Error - Returned if there is an unexpected
            error.
      security:
      - userAuth:
        - sp:scopes:default
      summary: Get list of public identities
      tags:
      - Public Identities
      x-sailpoint-userLevels:
      - USER
components:
  parameters:
    limit:
      description: |-
        Max number of results to return.
        See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
      example: 250
      explode: true
      in: query
      name: limit
      required: false
      schema:
        default: 250
        format: int32
        maximum: 250
        minimum: 0
        type: integer
      style: form
    offset:
      description: |-
        Offset into the full result set. Usually specified with *limit* to paginate through the results.
        See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
      example: 0
      explode: true
      in: query
      name: offset
      required: false
      schema:
        default: 0
        format: int32
        minimum: 0
        type: integer
      style: form
    count:
      description: |-
        If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.

        Since requesting a total count can have a performance impact, it is recommended not to send **count=true** if that value will not be used.

        See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
      example: true
      explode: true
      in: query
      name: count
      required: false
      schema:
        default: false
        type: boolean
      style: form
  responses:
    "400":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorresponsedto'
      description: Client Error - Returned if the request body is invalid.
    "401":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/getPublicIdentitiesV1_401_response'
      description: "Unauthorized - Returned if there is no authorization header, or\
        \ if the JWT token is expired."
    "403":
      content:
        application/json:
          examples:
            "403":
              summary: An example of a 403 response object
              value:
                detailCode: 403 Forbidden
                trackingId: b21b1f7ce4da4d639f2c62a57171b427
                messages:
                - locale: en-US
                  localeOrigin: DEFAULT
                  text: The server understood the request but refuses to authorize
                    it.
          schema:
            $ref: '#/components/schemas/errorresponsedto'
      description: "Forbidden - Returned if the user you are running as, doesn't have\
        \ access to this end-point."
    "429":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/getPublicIdentitiesV1_429_response'
      description: Too Many Requests - Returned in response to too many requests in
        a given period of time - rate limited. The Retry-After header in the response
        includes how long to wait before trying again.
    "500":
      content:
        application/json:
          examples:
            "500":
              summary: An example of a 500 response object
              value:
                detailCode: 500.0 Internal Fault
                trackingId: b21b1f7ce4da4d639f2c62a57171b427
                messages:
                - locale: en-US
                  localeOrigin: DEFAULT
                  text: An internal fault occurred.
          schema:
            $ref: '#/components/schemas/errorresponsedto'
      description: Internal Server Error - Returned if there is an unexpected error.
  schemas:
    dtotype:
      description: An enumeration of the types of DTOs supported within the IdentityNow
        infrastructure.
      enum:
      - ACCOUNT_CORRELATION_CONFIG
      - ACCESS_PROFILE
      - ACCESS_REQUEST_APPROVAL
      - ACCOUNT
      - APPLICATION
      - CAMPAIGN
      - CAMPAIGN_FILTER
      - CERTIFICATION
      - CLUSTER
      - CONNECTOR_SCHEMA
      - ENTITLEMENT
      - GOVERNANCE_GROUP
      - IDENTITY
      - IDENTITY_PROFILE
      - IDENTITY_REQUEST
      - MACHINE_IDENTITY
      - LIFECYCLE_STATE
      - PASSWORD_POLICY
      - ROLE
      - RULE
      - SOD_POLICY
      - SOURCE
      - TAG
      - TAG_CATEGORY
      - TASK_RESULT
      - REPORT_RESULT
      - SOD_VIOLATION
      - ACCOUNT_ACTIVITY
      - WORKGROUP
      example: IDENTITY
      type: string
    identityreference:
      description: The manager for the identity.
      example:
        name: Thomas Edison
        id: 2c9180a46faadee4016fb4e018c20639
        type: IDENTITY
      nullable: true
      properties:
        type:
          $ref: '#/components/schemas/dtotype'
        id:
          description: Identity id
          example: 2c9180a46faadee4016fb4e018c20639
          type: string
        name:
          description: Human-readable display name of identity.
          example: Thomas Edison
          type: string
      title: Identity Reference
      type: object
    publicidentity:
      description: Details about a public identity
      example:
        manager:
          name: Thomas Edison
          id: 2c9180a46faadee4016fb4e018c20639
          type: IDENTITY
        name: Alison Ferguso
        alias: alison.ferguso
        attributes:
        - name: Country
          value: US
          key: country
        - name: Country
          value: US
          key: country
        id: 2c9180857182305e0171993735622948
        identityState: ACTIVE
        email: alison.ferguso@acme-solar.com
        status: Active
      properties:
        id:
          description: Identity id
          example: 2c9180857182305e0171993735622948
          type: string
        name:
          description: Human-readable display name of identity.
          example: Alison Ferguso
          type: string
        alias:
          description: Alternate unique identifier for the identity.
          example: alison.ferguso
          type: string
        email:
          description: Email address of identity.
          example: alison.ferguso@acme-solar.com
          nullable: true
          type: string
        status:
          description: The lifecycle status for the identity
          example: Active
          nullable: true
          type: string
        identityState:
          description: |
            The current state of the identity, which determines how Identity Security Cloud interacts with the identity.
            An identity that is Active will be included identity picklists in Request Center, identity processing, and more.
            Identities that are Inactive will be excluded from these features.
          enum:
          - ACTIVE
          - INACTIVE_SHORT_TERM
          - INACTIVE_LONG_TERM
          - null
          example: ACTIVE
          nullable: true
          type: string
        manager:
          $ref: '#/components/schemas/identityreference'
        attributes:
          description: The public identity attributes of the identity
          items:
            $ref: '#/components/schemas/publicidentity_attributes_inner'
          type: array
      title: Public Identity
      type: object
    localeorigin:
      description: "An indicator of how the locale was selected. *DEFAULT* means the\
        \ locale is the system default. *REQUEST* means the locale was selected from\
        \ the request context (i.e., best match based on the *Accept-Language* header).\
        \ Additional values may be added in the future without notice."
      enum:
      - DEFAULT
      - REQUEST
      - null
      example: DEFAULT
      nullable: true
      type: string
    errormessagedto:
      example:
        localeOrigin: DEFAULT
        text: The request was syntactically correct but its content is semantically
          invalid.
        locale: en-US
      properties:
        locale:
          description: "The locale for the message text, a BCP 47 language tag."
          example: en-US
          nullable: true
          type: string
        localeOrigin:
          $ref: '#/components/schemas/localeorigin'
        text:
          description: Actual text of the error message in the indicated locale.
          example: The request was syntactically correct but its content is semantically
            invalid.
          type: string
      title: Error Message Dto
      type: object
    errorresponsedto:
      example:
        causes:
        - localeOrigin: DEFAULT
          text: The request was syntactically correct but its content is semantically
            invalid.
          locale: en-US
        - localeOrigin: DEFAULT
          text: The request was syntactically correct but its content is semantically
            invalid.
          locale: en-US
        messages:
        - localeOrigin: DEFAULT
          text: The request was syntactically correct but its content is semantically
            invalid.
          locale: en-US
        - localeOrigin: DEFAULT
          text: The request was syntactically correct but its content is semantically
            invalid.
          locale: en-US
        detailCode: 400.1 Bad Request Content
        trackingId: e7eab60924f64aa284175b9fa3309599
      properties:
        detailCode:
          description: Fine-grained error code providing more detail of the error.
          example: 400.1 Bad Request Content
          type: string
        trackingId:
          description: Unique tracking id for the error.
          example: e7eab60924f64aa284175b9fa3309599
          type: string
        messages:
          description: Generic localized reason for error
          items:
            $ref: '#/components/schemas/errormessagedto'
          type: array
        causes:
          description: Plain-text descriptive reasons to provide additional detail
            to the text provided in the messages field
          items:
            $ref: '#/components/schemas/errormessagedto'
          type: array
      title: Error Response Dto
      type: object
    getPublicIdentitiesV1_401_response:
      example:
        error: "JWT validation failed: JWT is expired"
      properties:
        error:
          description: A message describing the error
          example: "JWT validation failed: JWT is expired"
      type: object
    getPublicIdentitiesV1_429_response:
      example:
        message: ' Rate Limit Exceeded '
      properties:
        message:
          description: A message describing the error
          example: ' Rate Limit Exceeded '
      type: object
    publicidentity_attributes_inner:
      example:
        name: Country
        value: US
        key: country
      properties:
        key:
          description: The attribute key
          example: country
          type: string
        name:
          description: Human-readable display name of the attribute
          example: Country
          type: string
        value:
          description: The attribute value
          example: US
          nullable: true
          type: string
      type: object
