openapi: 3.0.1
info:
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  description: "Use these APIs to interact with the Identity Security Cloud platform\
    \ to achieve repeatable, automated processes with greater scalability. We encourage\
    \ you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss\
    \ to connect with other developers using our APIs."
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://developer.sailpoint.com/discuss/tos
  title: Identity Security Cloud API - Reports Data Extraction
  version: v1
servers:
- description: This is the production API server.
  url: "https://{tenant}.api.identitynow.com"
  variables:
    tenant:
      default: sailpoint
      description: "This is the name of your tenant, typically your company's name."
- description: This is the versioned API server.
  url: "https://{apiUrl}"
  variables:
    apiUrl:
      default: sailpoint.api.identitynow.com
      description: This is the api url of your tenant
security:
- userAuth:
  - sp:scopes:all
tags:
- description: "Use this API to implement reports lifecycle managing and monitoring.\n\
    With this functionality in place, users can run reports, view their results, and\
    \ cancel reports in progress. \nThis can be potentially helpful for auditing purposes.\
    \ \n"
  name: Reports Data Extraction
paths:
  /reports/v1/{taskResultId}/result:
    get:
      description: Get the report results for a report that was run or is running.
        Returns empty report result in case there are no active task definitions with
        used in payload task definition name.
      operationId: getReportResultV1
      parameters:
      - description: Unique identifier of the task result which handled report
        example: ef38f94347e94562b5bb8424a56397d8
        explode: false
        in: path
        name: taskResultId
        required: true
        schema:
          type: string
        style: simple
        x-sailpoint-resource-operation-id: startReport
      - description: state of task result to apply ordering when results are fetching
          from the DB
        example: true
        explode: true
        in: query
        name: completed
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              examples:
                identityDetailsReport:
                  $ref: '#/components/examples/identities-details-report-results'
              schema:
                $ref: '#/components/schemas/reportresults'
          description: Details about report that was run or is running.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Client Error - Returned if the request body is invalid.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getReportResultV1_401_response'
          description: "Unauthorized - Returned if there is no authorization header,\
            \ or if the JWT token is expired."
        "403":
          content:
            application/json:
              examples:
                "403":
                  summary: An example of a 403 response object
                  value:
                    detailCode: 403 Forbidden
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server understood the request but refuses to authorize
                        it.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: "Forbidden - Returned if the user you are running as, doesn't\
            \ have access to this end-point."
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getReportResultV1_429_response'
          description: Too Many Requests - Returned in response to too many requests
            in a given period of time - rate limited. The Retry-After header in the
            response includes how long to wait before trying again.
        "500":
          content:
            application/json:
              examples:
                "500":
                  summary: An example of a 500 response object
                  value:
                    detailCode: 500.0 Internal Fault
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: An internal fault occurred.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Internal Server Error - Returned if there is an unexpected
            error.
      security:
      - userAuth:
        - sp:report:read
        - sp:report:manage
      - applicationAuth:
        - sp:report:read
        - sp:report:manage
      summary: Get report result
      tags:
      - Reports Data Extraction
  /reports/v1/run:
    post:
      description: "Use this API to run a report according to report input details.\
        \ If non-concurrent task is already running then it returns, otherwise new\
        \ task creates and returns."
      operationId: startReportV1
      requestBody:
        content:
          application/json:
            examples:
              Account Export Report:
                $ref: '#/components/examples/account-export-report-details'
              Identities Details Report:
                $ref: '#/components/examples/identities-details-report-details'
              Identities Report:
                $ref: '#/components/examples/identities-report-details'
              Identity Profile Identity Error Report:
                $ref: '#/components/examples/identity-profile-identity-error-report-details'
              Orphan Identities Report:
                $ref: '#/components/examples/orphan-identities-report-details'
              Search Export Report:
                $ref: '#/components/examples/search-export-report-details'
              Uncorrelated Accounts Report:
                $ref: '#/components/examples/uncorrelated-accounts-report-details'
            schema:
              $ref: '#/components/schemas/reportdetails'
        required: true
      responses:
        "200":
          content:
            application/json:
              examples:
                identityDetailsReport:
                  $ref: '#/components/examples/identities-details-report-task-result'
                searchExportReport:
                  $ref: '#/components/examples/search-export-report-task-result'
              schema:
                $ref: '#/components/schemas/taskresultdetails'
          description: Details about running report task.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Client Error - Returned if the request body is invalid.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getReportResultV1_401_response'
          description: "Unauthorized - Returned if there is no authorization header,\
            \ or if the JWT token is expired."
        "403":
          content:
            application/json:
              examples:
                "403":
                  summary: An example of a 403 response object
                  value:
                    detailCode: 403 Forbidden
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server understood the request but refuses to authorize
                        it.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: "Forbidden - Returned if the user you are running as, doesn't\
            \ have access to this end-point."
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getReportResultV1_429_response'
          description: Too Many Requests - Returned in response to too many requests
            in a given period of time - rate limited. The Retry-After header in the
            response includes how long to wait before trying again.
        "500":
          content:
            application/json:
              examples:
                "500":
                  summary: An example of a 500 response object
                  value:
                    detailCode: 500.0 Internal Fault
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: An internal fault occurred.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Internal Server Error - Returned if there is an unexpected
            error.
      security:
      - userAuth:
        - sp:report:manage
      - applicationAuth:
        - sp:report:manage
      summary: Run report
      tags:
      - Reports Data Extraction
      x-sailpoint-userLevels:
      - ORG_ADMIN
      - CERT_ADMIN
      - REPORT_ADMIN
      - ROLE_ADMIN
      - ROLE_SUBADMIN
      - SOURCE_ADMIN
      - SOURCE_SUBADMIN
  /reports/v1/{id}/cancel:
    post:
      description: Cancels a running report.
      operationId: cancelReportV1
      parameters:
      - description: ID of the running Report to cancel
        explode: false
        in: path
        name: id
        required: true
        schema:
          example: a1ed223247144cc29d23c632624b4767
          type: string
        style: simple
        x-sailpoint-resource-operation-id: startReport
      responses:
        "204":
          description: No content - indicates the request was successful but there
            is no content to be returned in the response.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Client Error - Returned if the request body is invalid.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getReportResultV1_401_response'
          description: "Unauthorized - Returned if there is no authorization header,\
            \ or if the JWT token is expired."
        "403":
          content:
            application/json:
              examples:
                "403":
                  summary: An example of a 403 response object
                  value:
                    detailCode: 403 Forbidden
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server understood the request but refuses to authorize
                        it.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: "Forbidden - Returned if the user you are running as, doesn't\
            \ have access to this end-point."
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getReportResultV1_429_response'
          description: Too Many Requests - Returned in response to too many requests
            in a given period of time - rate limited. The Retry-After header in the
            response includes how long to wait before trying again.
        "500":
          content:
            application/json:
              examples:
                "500":
                  summary: An example of a 500 response object
                  value:
                    detailCode: 500.0 Internal Fault
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: An internal fault occurred.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Internal Server Error - Returned if there is an unexpected
            error.
      security:
      - userAuth:
        - sp:report:manage
      summary: Cancel report
      tags:
      - Reports Data Extraction
  /reports/v1/{taskResultId}:
    get:
      description: Gets a report in file format.
      operationId: getReportV1
      parameters:
      - description: Unique identifier of the task result which handled report
        example: ef38f94347e94562b5bb8424a56397d8
        explode: false
        in: path
        name: taskResultId
        required: true
        schema:
          type: string
        style: simple
        x-sailpoint-resource-operation-id: startReport
      - description: Output format of the requested report file
        example: csv
        explode: true
        in: query
        name: fileFormat
        required: true
        schema:
          enum:
          - csv
          - pdf
          type: string
        style: form
      - description: "preferred Report file name, by default will be used report name\
          \ from task result."
        example: Identities Details Report
        explode: true
        in: query
        name: name
        required: false
        schema:
          type: string
        style: form
      - description: Enables auditing for current report download. Will create an
          audit event and sent it to the REPORT cloud-audit kafka topic.  Event will
          be created if there is any result present by requested taskResultId.
        example: true
        explode: true
        in: query
        name: auditable
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/csv:
              schema:
                format: binary
                type: string
            application/pdf:
              schema:
                format: binary
                type: string
          description: Report file in selected format. CSV by default.
          headers:
            Content-disposition:
              description: The requested report's filename
              example: attachment;filename=\"fileName"
              explode: false
              schema:
                type: string
              style: simple
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Client Error - Returned if the request body is invalid.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getReportResultV1_401_response'
          description: "Unauthorized - Returned if there is no authorization header,\
            \ or if the JWT token is expired."
        "403":
          content:
            application/json:
              examples:
                "403":
                  summary: An example of a 403 response object
                  value:
                    detailCode: 403 Forbidden
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server understood the request but refuses to authorize
                        it.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: "Forbidden - Returned if the user you are running as, doesn't\
            \ have access to this end-point."
        "404":
          content:
            application/json:
              examples:
                "404":
                  summary: An example of a 404 response object
                  value:
                    detailCode: 404 Not found
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: <h1>File Not Found - 404 Error</h1> The requested file
                        was not found.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Not Found - returned if the request URL refers to a resource
            or object that does not exist
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getReportResultV1_429_response'
          description: Too Many Requests - Returned in response to too many requests
            in a given period of time - rate limited. The Retry-After header in the
            response includes how long to wait before trying again.
        "500":
          content:
            application/json:
              examples:
                "500":
                  summary: An example of a 500 response object
                  value:
                    detailCode: 500.0 Internal Fault
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: An internal fault occurred.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Internal Server Error - Returned if there is an unexpected
            error.
      security:
      - userAuth:
        - sp:report:read
        - sp:report:manage
      - applicationAuth:
        - sp:report:read
        - sp:report:manage
      summary: Get report file
      tags:
      - Reports Data Extraction
components:
  examples:
    identities-details-report-results:
      summary: Identities details report result.
      value:
        reportType: IDENTITIES_DETAILS
        taskDefName: Identities Details Report
        id: 1e01d272b8084c4fa12fcf8fa898102d
        created: 2023-09-07T42:14:05.122Z
        status: SUCCESS
        duration: 3681
        rows: 193
        availableFormats:
        - CSV
    account-export-report-details:
      summary: Account export report
      value:
        reportType: ACCOUNTS
        arguments:
          application: 2c9180897eSourceIde781782f705b9
          sourceName: Active Directory
    identities-details-report-details:
      summary: Identities details report
      value:
        reportType: IDENTITIES_DETAILS
        arguments:
          correlatedOnly: true
    identities-report-details:
      summary: Identities report
      value:
        reportType: IDENTITIES
        arguments:
          correlatedOnly: true
    identity-profile-identity-error-report-details:
      summary: Identity profile identity error report
      value:
        reportType: IDENTITY_PROFILE_IDENTITY_ERROR
        arguments:
          authoritativeSource: 2c9180847de347aa017de8ef09167792
    orphan-identities-report-details:
      summary: Orphan identities report
      value:
        reportType: ORPHAN_IDENTITIES
        arguments:
          selectedFormats:
          - CSV
          - PDF
    search-export-report-details:
      summary: Search export report
      value:
        reportType: SEARCH_EXPORT
        arguments:
          indices:
          - identities
          query: attributes.city:London
          columns: "displayName,firstName,lastName,email,attributes.city,created,attributes.cloudLifecycleState,access.spread"
          sort:
          - +displayName
    uncorrelated-accounts-report-details:
      summary: Uncorrelated accounts report
      value:
        reportType: UNCORRELATED_ACCOUNTS
        arguments:
          selectedFormats:
          - CSV
          - PDF
    identities-details-report-task-result:
      summary: Identities details report task result.
      value:
        reportType: IDENTITIES_DETAILS
        taskDefName: Identities Details Report
        type: QUARTZ
        id: a248c16fe22222b2bd49615481311111
        created: 2023-09-07T42:14:00.364Z
        description: A detailed view of the identities in the system.
        parentName: Audit Report
        launcher: "9832285"
        launched: 2023-09-07T42:14:00.521Z
        completed: 2023-09-07T42:14:01.137Z
        messages: []
        returns: []
        attributes:
          org: an-org
        progress: Initializing...
    search-export-report-task-result:
      summary: Identities details report task result.
      value:
        reportType: SEARCH_EXPORT
        taskDefName: Search Export
        type: QUARTZ
        id: a248c16fe22222b2bd49615481311111
        created: 2023-09-07T42:14:11.137Z
        description: Extract query data from ElasticSearch to CSV
        parentName: null
        launcher: T05293
        launched: 2020-09-07T42:14:11.137Z
        completed: 2020-09-07T42:14:13.451Z
        messages: []
        returns: []
        attributes:
          queryHash: 5e12cf79c67d92e23d4d8cb3e974f87d164e86d4a48d32ecf89645cacfd3f2
          org: an-org
          queryParams:
            columns: "displayName,firstName,lastName,email,created,attributes.cloudLifecycleState,tags,access.spread,apps.pread,accounts.spread"
            indices: identities
            ownerId: 95ecba5c5444439c999aec638ce2a777
            query: 700007
            sort: displayName
        progress: Initializing...
  responses:
    "204":
      description: No content - indicates the request was successful but there is
        no content to be returned in the response.
    "400":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorresponsedto'
      description: Client Error - Returned if the request body is invalid.
    "401":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/getReportResultV1_401_response'
      description: "Unauthorized - Returned if there is no authorization header, or\
        \ if the JWT token is expired."
    "403":
      content:
        application/json:
          examples:
            "403":
              summary: An example of a 403 response object
              value:
                detailCode: 403 Forbidden
                trackingId: b21b1f7ce4da4d639f2c62a57171b427
                messages:
                - locale: en-US
                  localeOrigin: DEFAULT
                  text: The server understood the request but refuses to authorize
                    it.
          schema:
            $ref: '#/components/schemas/errorresponsedto'
      description: "Forbidden - Returned if the user you are running as, doesn't have\
        \ access to this end-point."
    "429":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/getReportResultV1_429_response'
      description: Too Many Requests - Returned in response to too many requests in
        a given period of time - rate limited. The Retry-After header in the response
        includes how long to wait before trying again.
    "500":
      content:
        application/json:
          examples:
            "500":
              summary: An example of a 500 response object
              value:
                detailCode: 500.0 Internal Fault
                trackingId: b21b1f7ce4da4d639f2c62a57171b427
                messages:
                - locale: en-US
                  localeOrigin: DEFAULT
                  text: An internal fault occurred.
          schema:
            $ref: '#/components/schemas/errorresponsedto'
      description: Internal Server Error - Returned if there is an unexpected error.
  schemas:
    reportresults:
      description: Details about report result or current state.
      example:
        reportType: IDENTITIES_DETAILS
        duration: 342
        availableFormats:
        - CSV
        created: 2000-01-23T04:56:07.000+00:00
        taskDefName: Identities Details Report
        id: a248c16fe22222b2bd49615481311111
        rows: 37
        status: SUCCESS
      properties:
        reportType:
          description: Use this property to define what report should be processed
            in the RDE service.
          enum:
          - ACCOUNTS
          - IDENTITIES_DETAILS
          - IDENTITIES
          - IDENTITY_PROFILE_IDENTITY_ERROR
          - ORPHAN_IDENTITIES
          - SEARCH_EXPORT
          - UNCORRELATED_ACCOUNTS
          example: IDENTITIES_DETAILS
          type: string
        taskDefName:
          description: Name of the task definition which is started to process requesting
            report. Usually the same as report name
          example: Identities Details Report
          type: string
        id:
          description: Unique task definition identifier.
          example: a248c16fe22222b2bd49615481311111
          type: string
        created:
          description: Report processing start date
          format: date-time
          type: string
        status:
          description: Report current state or result status.
          enum:
          - SUCCESS
          - FAILURE
          - WARNING
          - TERMINATED
          example: SUCCESS
          type: string
        duration:
          description: Report processing time in ms.
          example: 342
          format: int64
          type: integer
        rows:
          description: Report size in rows.
          example: 37
          format: int64
          type: integer
        availableFormats:
          description: "Output report file formats. This are formats for calling get\
            \ endpoint as a query parameter 'fileFormat'.  In case report won't have\
            \ this argument there will be ['CSV', 'PDF'] as default."
          example:
          - CSV
          items:
            enum:
            - CSV
            - PDF
            type: string
          type: array
      type: object
    localeorigin:
      description: "An indicator of how the locale was selected. *DEFAULT* means the\
        \ locale is the system default. *REQUEST* means the locale was selected from\
        \ the request context (i.e., best match based on the *Accept-Language* header).\
        \ Additional values may be added in the future without notice."
      enum:
      - DEFAULT
      - REQUEST
      - null
      example: DEFAULT
      nullable: true
      type: string
    errormessagedto:
      example:
        localeOrigin: DEFAULT
        text: The request was syntactically correct but its content is semantically
          invalid.
        locale: en-US
      properties:
        locale:
          description: "The locale for the message text, a BCP 47 language tag."
          example: en-US
          nullable: true
          type: string
        localeOrigin:
          $ref: '#/components/schemas/localeorigin'
        text:
          description: Actual text of the error message in the indicated locale.
          example: The request was syntactically correct but its content is semantically
            invalid.
          type: string
      title: Error Message Dto
      type: object
    errorresponsedto:
      example:
        causes:
        - localeOrigin: DEFAULT
          text: The request was syntactically correct but its content is semantically
            invalid.
          locale: en-US
        - localeOrigin: DEFAULT
          text: The request was syntactically correct but its content is semantically
            invalid.
          locale: en-US
        messages:
        - localeOrigin: DEFAULT
          text: The request was syntactically correct but its content is semantically
            invalid.
          locale: en-US
        - localeOrigin: DEFAULT
          text: The request was syntactically correct but its content is semantically
            invalid.
          locale: en-US
        detailCode: 400.1 Bad Request Content
        trackingId: e7eab60924f64aa284175b9fa3309599
      properties:
        detailCode:
          description: Fine-grained error code providing more detail of the error.
          example: 400.1 Bad Request Content
          type: string
        trackingId:
          description: Unique tracking id for the error.
          example: e7eab60924f64aa284175b9fa3309599
          type: string
        messages:
          description: Generic localized reason for error
          items:
            $ref: '#/components/schemas/errormessagedto'
          type: array
        causes:
          description: Plain-text descriptive reasons to provide additional detail
            to the text provided in the messages field
          items:
            $ref: '#/components/schemas/errormessagedto'
          type: array
      title: Error Response Dto
      type: object
    accounts-export-report-arguments:
      description: Arguments for Account Export report (ACCOUNTS)
      properties:
        application:
          description: Source ID.
          example: 2c9180897eSourceIde781782f705b9
          type: string
        sourceName:
          description: Source name.
          example: Active Directory
          type: string
      required:
      - application
      - sourceName
      title: ACCOUNTS
      type: object
    identities-details-report-arguments:
      description: Arguments for Identities Details report (IDENTITIES_DETAILS)
      properties:
        correlatedOnly:
          default: false
          description: Flag to specify if only correlated identities are included
            in report.
          example: true
          type: boolean
      required:
      - correlatedOnly
      title: IDENTITIES_DETAILS
      type: object
    identities-report-arguments:
      description: Arguments for Identities report (IDENTITIES)
      properties:
        correlatedOnly:
          default: false
          description: Flag to specify if only correlated identities are included
            in report.
          example: true
          type: boolean
      title: IDENTITIES
      type: object
    identity-profile-identity-error-report-arguments:
      description: Arguments for Identity Profile Identity Error report (IDENTITY_PROFILE_IDENTITY_ERROR)
      properties:
        authoritativeSource:
          description: Source ID.
          example: 1234sourceId5678902
          type: string
      required:
      - authoritativeSource
      title: IDENTITY_PROFILE_IDENTITY_ERROR
      type: object
    orphan-identities-report-arguments:
      description: Arguments for Orphan Identities report (ORPHAN_IDENTITIES)
      properties:
        selectedFormats:
          description: "Output report file formats. These are formats for calling\
            \ GET endpoint as query parameter 'fileFormat'.  In case report won't\
            \ have this argument there will be ['CSV', 'PDF'] as default."
          example:
          - CSV
          items:
            enum:
            - CSV
            - PDF
            type: string
          type: array
      title: ORPHAN_IDENTITIES
      type: object
    index:
      description: |-
        Enum representing the currently supported indices.
        Additional values may be added in the future without notice.
      enum:
      - accessprofiles
      - accountactivities
      - entitlements
      - events
      - identities
      - roles
      - '*'
      example: identities
      type: string
    search-export-report-arguments:
      description: |
        Arguments for Search Export report (SEARCH_EXPORT)

        The report file generated will be a zip file containing csv files of the search results.
      properties:
        indices:
          description: "The names of the Elasticsearch indices in which to search.\
            \ If none are provided, then all indices will be searched."
          example:
          - entitlements
          externalDocs:
            description: Learn more about search indices here.
            url: https://documentation.sailpoint.com/saas/help/search/searchable-fields.html
          items:
            $ref: '#/components/schemas/index'
          type: array
        query:
          description: "The query using the Elasticsearch [Query String Query](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/query-dsl-query-string-query.html#query-string)\
            \ syntax from the Query DSL extended by SailPoint to support Nested queries."
          example: name:a*
          type: string
        columns:
          description: |
            Comma separated string consisting of technical attribute names of fields to include in report.

            Use `access.spread`, `apps.spread`, `accounts.spread` to include respective identity access details.

            Use `accessProfiles.spread` to unclude access profile details.

            Use `entitlements.spread` to include entitlement details.
          example: "displayName,firstName,lastName,email,created,attributes.cloudLifecycleState"
          type: string
        sort:
          description: The fields to be used to sort the search results. Use + or
            - to specify the sort direction.
          example:
          - displayName
          - +id
          items:
            type: string
          type: array
      required:
      - query
      title: SEARCH_EXPORT
      type: object
    uncorrelated-accounts-report-arguments:
      description: Arguments for Uncorrelated Accounts report (UNCORRELATED_ACCOUNTS)
      properties:
        selectedFormats:
          description: "Output report file formats. These are formats for calling\
            \ GET endpoint as query parameter 'fileFormat'.  In case report won't\
            \ have this argument there will be ['CSV', 'PDF'] as default."
          example:
          - CSV
          items:
            enum:
            - CSV
            - PDF
            type: string
          type: array
      title: UNCORRELATED_ACCOUNTS
      type: object
    reportdetails:
      description: Details about report to be processed.
      properties:
        reportType:
          description: Use this property to define what report should be processed
            in the RDE service.
          enum:
          - ACCOUNTS
          - IDENTITIES_DETAILS
          - IDENTITIES
          - IDENTITY_PROFILE_IDENTITY_ERROR
          - ORPHAN_IDENTITIES
          - SEARCH_EXPORT
          - UNCORRELATED_ACCOUNTS
          example: ACCOUNTS
          type: string
        arguments:
          $ref: '#/components/schemas/reportdetails_arguments'
      type: object
    taskresultdetails:
      description: "Details about job or task type, state and lifecycle."
      example:
        created: 2000-01-23T04:56:07.000+00:00
        description: A detailed view of the identities in the system.
        completed: 2000-01-23T04:56:07.000+00:00
        type: MENTOS
        launched: 2000-01-23T04:56:07.000+00:00
        reportType: IDENTITIES_DETAILS
        parentName: Audit Report
        messages: []
        progress: Initializing...
        returns: []
        attributes:
          org: an-org
        id: a248c16fe22222b2bd49615481311111
        completionStatus: Success
        launcher: cloudadmin
      properties:
        type:
          description: "Type of the job or task underlying in the report processing.\
            \ It could be a quartz task, QPOC or MENTOS jobs or a refresh/sync task."
          enum:
          - QUARTZ
          - QPOC
          - MENTOS
          - QUEUED_TASK
          example: MENTOS
          type: string
        id:
          description: Unique task definition identifier.
          example: a248c16fe22222b2bd49615481311111
          type: string
        reportType:
          description: Use this property to define what report should be processed
            in the RDE service.
          enum:
          - ACCOUNTS
          - IDENTITIES_DETAILS
          - IDENTITIES
          - IDENTITY_PROFILE_IDENTITY_ERROR
          - ORPHAN_IDENTITIES
          - SEARCH_EXPORT
          - UNCORRELATED_ACCOUNTS
          example: IDENTITIES_DETAILS
          type: string
        description:
          description: Description of the report purpose and/or contents.
          example: A detailed view of the identities in the system.
          type: string
        parentName:
          description: Name of the parent task/report if exists.
          example: Audit Report
          nullable: true
          type: string
        launcher:
          description: Name of the report processing initiator.
          example: cloudadmin
          type: string
        created:
          description: Report creation date
          format: date-time
          type: string
        launched:
          description: Report start date
          format: date-time
          nullable: true
          type: string
        completed:
          description: Report completion date
          format: date-time
          nullable: true
          type: string
        completionStatus:
          description: Report completion status.
          enum:
          - SUCCESS
          - WARNING
          - ERROR
          - TERMINATED
          - TEMP_ERROR
          example: Success
          nullable: true
          type: string
        messages:
          description: List of the messages dedicated to the report.  From task definition
            perspective here usually should be warnings or errors.
          example: []
          items:
            $ref: '#/components/schemas/taskresultdetails_messages_inner'
          type: array
        returns:
          description: "Task definition results, if necessary."
          example: []
          items:
            $ref: '#/components/schemas/taskresultdetails_returns_inner'
          type: array
        attributes:
          description: Extra attributes map(dictionary) needed for the report.
          example:
            org: an-org
          type: object
        progress:
          description: Current report state.
          example: Initializing...
          nullable: true
          type: string
      type: object
    getReportResultV1_401_response:
      example:
        error: "JWT validation failed: JWT is expired"
      properties:
        error:
          description: A message describing the error
          example: "JWT validation failed: JWT is expired"
      type: object
    getReportResultV1_429_response:
      example:
        message: ' Rate Limit Exceeded '
      properties:
        message:
          description: A message describing the error
          example: ' Rate Limit Exceeded '
      type: object
    reportdetails_arguments:
      anyOf:
      - $ref: '#/components/schemas/accounts-export-report-arguments'
      - $ref: '#/components/schemas/identities-details-report-arguments'
      - $ref: '#/components/schemas/identities-report-arguments'
      - $ref: '#/components/schemas/identity-profile-identity-error-report-arguments'
      - $ref: '#/components/schemas/orphan-identities-report-arguments'
      - $ref: '#/components/schemas/search-export-report-arguments'
      - $ref: '#/components/schemas/uncorrelated-accounts-report-arguments'
      description: The string-object map(dictionary) with the arguments needed for
        report processing.
      example:
        application: 2c9180897e7742b2017e781782f705b9
        sourceName: Active Directory
    taskresultdetails_messages_inner:
      properties:
        type:
          description: Type of the message.
          enum:
          - INFO
          - WARN
          - ERROR
          example: WARN
          type: string
        error:
          default: false
          description: Flag whether message is an error.
          example: false
          type: boolean
        warning:
          default: false
          description: Flag whether message is a warning.
          example: true
          type: boolean
        key:
          description: Message string identifier.
          example: "The following account(s) failed to correlate: A,B,C"
          type: string
        localizedText:
          description: Message context with the locale based language.
          example: "The following account(s) failed to correlate: A,B,C"
          type: string
      type: object
    taskresultdetails_returns_inner:
      properties:
        displayLabel:
          description: Attribute description.
          example: ' '
          type: string
        attributeName:
          description: System or database attribute name.
          example: ' '
          type: string
      type: object
