openapi: 3.0.1
info:
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  description: "Use these APIs to interact with the Identity Security Cloud platform\
    \ to achieve repeatable, automated processes with greater scalability. We encourage\
    \ you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss\
    \ to connect with other developers using our APIs."
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://developer.sailpoint.com/discuss/tos
  title: Identity Security Cloud API - Scheduled Search
  version: v1
servers:
- description: This is the production API server.
  url: "https://{tenant}.api.identitynow.com"
  variables:
    tenant:
      default: sailpoint
      description: "This is the name of your tenant, typically your company's name."
- description: This is the versioned API server.
  url: "https://{apiUrl}"
  variables:
    apiUrl:
      default: sailpoint.api.identitynow.com
      description: This is the api url of your tenant
security:
- userAuth:
  - sp:scopes:all
tags:
- description: "Use this API to implement scheduled search functionality. \nWith scheduled\
    \ search functionality in place, users can run saved search queries on their tenants\
    \ on a schedule, and Identity Security Cloud emails them the search results. \n\
    Users can also share these search results with other users by email by adding\
    \ those users as subscribers, or those users can subscribe themselves. \n\nOne\
    \ of the greatest benefits of saving searches is the ability to run those searches\
    \ on a schedule. \nThis is essential for organizations to constantly detect any\
    \ changes to user information or access throughout their tenants and across all\
    \ their sources. \nFor example, the manager Amanda Ross can schedule a saved search\
    \ \"manager.name:amanda.ross AND attributes.location:austin\" on a schedule to\
    \ regularly stay aware of changes with the Austin employees reporting to her.\n\
    Identity Security Cloud emails her the search results when the search runs, so\
    \ she can work on other tasks instead of actively running this search.\n\nIn Identity\
    \ Security Cloud, scheduling a search involves a subscription. \nUsers can create\
    \ a subscription for a saved search and schedule it to run daily, weekly, or monthly\
    \ (you can only use one schedule option at a time). \nThe user can add other identities\
    \ as subscribers so when the scheduled search runs, the subscribers and the user\
    \ all receive emails. \n\nBy default, subscriptions exclude detailed results from\
    \ the emails, for security purposes. \nIncluding detailed results about user access\
    \ in an email may expose sensitive information.\nHowever, the subscription creator\
    \ can choose to include the information in the emails.  \n\nBy default, Identity\
    \ Security Cloud sends emails to the subscribers even when the searches do not\
    \ return new results. \nHowever, the subscription creator can choose to suppress\
    \ these empty emails. \n\nUsers can also subscribe to saved searches that already\
    \ have existing subscriptions so they receive emails when the searches run. \n\
    A saved search can have up to 10 subscriptions configured at a time. \n\nThe subscription\
    \ creator can enable, disable, or delete the subscription. \n\nRefer to [Subscribing\
    \ to Saved Searches](https://documentation.sailpoint.com/saas/help/search/saved-searches.html#subscribing-to-saved-searches)\
    \ for more information about scheduling searches and subscribing to them.\n"
  name: Scheduled Search
paths:
  /scheduled-searches/v1:
    get:
      description: |
        Returns a list of scheduled searches.
      operationId: listScheduledSearchV1
      parameters:
      - description: |-
          Offset into the full result set. Usually specified with *limit* to paginate through the results.
          See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
        example: 0
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          format: int32
          minimum: 0
          type: integer
        style: form
      - description: |-
          Max number of results to return.
          See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
        example: 250
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 250
          format: int32
          maximum: 250
          minimum: 0
          type: integer
        style: form
      - description: |-
          If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.

          Since requesting a total count can have a performance impact, it is recommended not to send **count=true** if that value will not be used.

          See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
        example: true
        explode: true
        in: query
        name: count
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - description: |-
          Filter results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#filtering-results)

          Filtering is supported for the following fields and operators:

          **owner.id**: *eq*

          **savedSearchId**: *eq*
        example: savedSearchId eq "6cc0945d-9eeb-4948-9033-72d066e1153e"
        explode: true
        in: query
        name: filters
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/scheduledsearch'
                type: array
          description: The list of requested scheduled searches.
          headers:
            X-Total-Count:
              description: The total result count (returned only if the *count* parameter
                is specified as *true*).
              example: 5
              explode: false
              schema:
                type: integer
              style: simple
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Client Error - Returned if the request body is invalid.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listScheduledSearchV1_401_response'
          description: "Unauthorized - Returned if there is no authorization header,\
            \ or if the JWT token is expired."
        "403":
          content:
            application/json:
              examples:
                "403":
                  summary: An example of a 403 response object
                  value:
                    detailCode: 403 Forbidden
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server understood the request but refuses to authorize
                        it.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: "Forbidden - Returned if the user you are running as, doesn't\
            \ have access to this end-point."
        "404":
          content:
            application/json:
              examples:
                "404":
                  summary: An example of a 404 response object
                  value:
                    detailCode: 404 Not found
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server did not find a current representation for the
                        target resource.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Not Found - returned if the request URL refers to a resource
            or object that does not exist
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listScheduledSearchV1_429_response'
          description: Too Many Requests - Returned in response to too many requests
            in a given period of time - rate limited. The Retry-After header in the
            response includes how long to wait before trying again.
        "500":
          content:
            application/json:
              examples:
                "500":
                  summary: An example of a 500 response object
                  value:
                    detailCode: 500.0 Internal Fault
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: An internal fault occurred.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Internal Server Error - Returned if there is an unexpected
            error.
      security:
      - userAuth:
        - sp:scheduled-search:manage
      summary: List scheduled searches
      tags:
      - Scheduled Search
    post:
      description: |
        Creates a new scheduled search.
      operationId: createScheduledSearchV1
      requestBody:
        content:
          application/json:
            examples:
              Daily Search:
                description: A search that executes each day at a 9 AM
                value:
                  savedSearchId: 9c620e13-cd33-4804-a13d-403bd7bcdbad
                  schedule:
                    type: DAILY
                    hours:
                      type: LIST
                      values:
                      - "9"
                  recipients:
                  - type: IDENTITY
                    id: 2c9180867624cbd7017642d8c8c81f67
              Weekly Search:
                description: A search that executes each week on select days and times
                value:
                  savedSearchId: 9c620e13-cd33-4804-a13d-403bd7bcdbad
                  schedule:
                    type: WEEKLY
                    days:
                      type: LIST
                      values:
                      - MON
                      - TUE
                      - WED
                      - THU
                      - FRI
                      - SAT
                      - SUN
                    hours:
                      type: LIST
                      values:
                      - "9"
                  recipients:
                  - type: IDENTITY
                    id: 2c9180867624cbd7017642d8c8c81f67
              Monthly Search:
                description: A search that executes each month on select days and
                  times
                value:
                  savedSearchId: 9c620e13-cd33-4804-a13d-403bd7bcdbad
                  schedule:
                    type: MONTHLY
                    days:
                      type: LIST
                      values:
                      - "1"
                      - "7"
                      - "14"
                      - L
                    hours:
                      type: LIST
                      values:
                      - "9"
                  recipients:
                  - type: IDENTITY
                    id: 2c9180867624cbd7017642d8c8c81f67
              Annual Search:
                description: "A search that executes each year on the defined months,\
                  \ days, and times."
                value:
                  savedSearchId: 9c620e13-cd33-4804-a13d-403bd7bcdbad
                  schedule:
                    type: ANNUALLY
                    months:
                      type: LIST
                      values:
                      - "1"
                      interval: 3
                    days:
                      type: LIST
                      values:
                      - "1"
                      - "7"
                      - "14"
                      - L
                    hours:
                      type: LIST
                      values:
                      - "9"
                  recipients:
                  - type: IDENTITY
                    id: 2c9180867624cbd7017642d8c8c81f67
              Calendar Search:
                description: A search that executes on specific calendar days
                value:
                  savedSearchId: 9c620e13-cd33-4804-a13d-403bd7bcdbad
                  schedule:
                    type: CALENDAR
                    days:
                      type: LIST
                      values:
                      - 2023-01-22
                      - 2023-02-22
                    hours:
                      type: LIST
                      values:
                      - "9"
                  recipients:
                  - type: IDENTITY
                    id: 2c9180867624cbd7017642d8c8c81f67
            schema:
              $ref: '#/components/schemas/createScheduledSearchV1_request'
        description: The scheduled search to persist.
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scheduledsearch'
          description: The persisted scheduled search.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Client Error - Returned if the request body is invalid.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listScheduledSearchV1_401_response'
          description: "Unauthorized - Returned if there is no authorization header,\
            \ or if the JWT token is expired."
        "403":
          content:
            application/json:
              examples:
                "403":
                  summary: An example of a 403 response object
                  value:
                    detailCode: 403 Forbidden
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server understood the request but refuses to authorize
                        it.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: "Forbidden - Returned if the user you are running as, doesn't\
            \ have access to this end-point."
        "404":
          content:
            application/json:
              examples:
                "404":
                  summary: An example of a 404 response object
                  value:
                    detailCode: 404 Not found
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server did not find a current representation for the
                        target resource.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Not Found - returned if the request URL refers to a resource
            or object that does not exist
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listScheduledSearchV1_429_response'
          description: Too Many Requests - Returned in response to too many requests
            in a given period of time - rate limited. The Retry-After header in the
            response includes how long to wait before trying again.
        "500":
          content:
            application/json:
              examples:
                "500":
                  summary: An example of a 500 response object
                  value:
                    detailCode: 500.0 Internal Fault
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: An internal fault occurred.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Internal Server Error - Returned if there is an unexpected
            error.
      security:
      - userAuth:
        - sp:scheduled-search:manage
      summary: Create a new scheduled search
      tags:
      - Scheduled Search
  /scheduled-searches/v1/{id}:
    delete:
      description: |
        Deletes the specified scheduled search.
      operationId: deleteScheduledSearchV1
      parameters:
      - description: ID of the requested document.
        example: 2c91808568c529c60168cca6f90c1313
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
        x-sailpoint-resource-operation-id: listScheduledSearchV1
      responses:
        "204":
          description: No Content - Indicates the request was successful but there
            is no content to be returned in the response.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Client Error - Returned if the request body is invalid.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listScheduledSearchV1_401_response'
          description: "Unauthorized - Returned if there is no authorization header,\
            \ or if the JWT token is expired."
        "403":
          content:
            application/json:
              examples:
                "403":
                  summary: An example of a 403 response object
                  value:
                    detailCode: 403 Forbidden
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server understood the request but refuses to authorize
                        it.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: "Forbidden - Returned if the user you are running as, doesn't\
            \ have access to this end-point."
        "404":
          content:
            application/json:
              examples:
                "404":
                  summary: An example of a 404 response object
                  value:
                    detailCode: 404 Not found
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server did not find a current representation for the
                        target resource.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Not Found - returned if the request URL refers to a resource
            or object that does not exist
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listScheduledSearchV1_429_response'
          description: Too Many Requests - Returned in response to too many requests
            in a given period of time - rate limited. The Retry-After header in the
            response includes how long to wait before trying again.
        "500":
          content:
            application/json:
              examples:
                "500":
                  summary: An example of a 500 response object
                  value:
                    detailCode: 500.0 Internal Fault
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: An internal fault occurred.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Internal Server Error - Returned if there is an unexpected
            error.
      security:
      - userAuth:
        - sp:scheduled-search:manage
      summary: Delete a scheduled search
      tags:
      - Scheduled Search
    get:
      description: Returns the specified scheduled search.
      operationId: getScheduledSearchV1
      parameters:
      - description: ID of the requested document.
        example: 2c91808568c529c60168cca6f90c1313
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
        x-sailpoint-resource-operation-id: listScheduledSearchV1
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scheduledsearch'
          description: The requested scheduled search.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Client Error - Returned if the request body is invalid.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listScheduledSearchV1_401_response'
          description: "Unauthorized - Returned if there is no authorization header,\
            \ or if the JWT token is expired."
        "403":
          content:
            application/json:
              examples:
                "403":
                  summary: An example of a 403 response object
                  value:
                    detailCode: 403 Forbidden
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server understood the request but refuses to authorize
                        it.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: "Forbidden - Returned if the user you are running as, doesn't\
            \ have access to this end-point."
        "404":
          content:
            application/json:
              examples:
                "404":
                  summary: An example of a 404 response object
                  value:
                    detailCode: 404 Not found
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server did not find a current representation for the
                        target resource.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Not Found - returned if the request URL refers to a resource
            or object that does not exist
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listScheduledSearchV1_429_response'
          description: Too Many Requests - Returned in response to too many requests
            in a given period of time - rate limited. The Retry-After header in the
            response includes how long to wait before trying again.
        "500":
          content:
            application/json:
              examples:
                "500":
                  summary: An example of a 500 response object
                  value:
                    detailCode: 500.0 Internal Fault
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: An internal fault occurred.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Internal Server Error - Returned if there is an unexpected
            error.
      security: []
      summary: Get a scheduled search
      tags:
      - Scheduled Search
    put:
      description: |
        Updates an existing scheduled search.
      operationId: updateScheduledSearchV1
      parameters:
      - description: ID of the requested document.
        example: 2c91808568c529c60168cca6f90c1313
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
        x-sailpoint-resource-operation-id: listScheduledSearchV1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/scheduledsearch'
        description: The scheduled search to persist.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scheduledsearch'
          description: The persisted scheduled search.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Client Error - Returned if the request body is invalid.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listScheduledSearchV1_401_response'
          description: "Unauthorized - Returned if there is no authorization header,\
            \ or if the JWT token is expired."
        "403":
          content:
            application/json:
              examples:
                "403":
                  summary: An example of a 403 response object
                  value:
                    detailCode: 403 Forbidden
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server understood the request but refuses to authorize
                        it.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: "Forbidden - Returned if the user you are running as, doesn't\
            \ have access to this end-point."
        "404":
          content:
            application/json:
              examples:
                "404":
                  summary: An example of a 404 response object
                  value:
                    detailCode: 404 Not found
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server did not find a current representation for the
                        target resource.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Not Found - returned if the request URL refers to a resource
            or object that does not exist
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listScheduledSearchV1_429_response'
          description: Too Many Requests - Returned in response to too many requests
            in a given period of time - rate limited. The Retry-After header in the
            response includes how long to wait before trying again.
        "500":
          content:
            application/json:
              examples:
                "500":
                  summary: An example of a 500 response object
                  value:
                    detailCode: 500.0 Internal Fault
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: An internal fault occurred.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Internal Server Error - Returned if there is an unexpected
            error.
      security:
      - userAuth:
        - sp:scheduled-search:manage
      summary: Update an existing scheduled search
      tags:
      - Scheduled Search
  /scheduled-searches/v1/{id}/unsubscribe:
    post:
      description: |
        Unsubscribes a recipient from the specified scheduled search.
      operationId: unsubscribeScheduledSearchV1
      parameters:
      - description: ID of the requested document.
        example: 2c91808568c529c60168cca6f90c1313
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
        x-sailpoint-resource-operation-id:
        - listAccessProfiles
        - listAccountActivities
        - listEntitlements
        - listRoles
        - listIdentities
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/typedreference'
        description: |
          The recipient to be removed from the scheduled search.
        required: true
      responses:
        "204":
          description: No Content - Indicates the request was successful but there
            is no content to be returned in the response.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Client Error - Returned if the request body is invalid.
        "403":
          content:
            application/json:
              examples:
                "403":
                  summary: An example of a 403 response object
                  value:
                    detailCode: 403 Forbidden
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server understood the request but refuses to authorize
                        it.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: "Forbidden - Returned if the user you are running as, doesn't\
            \ have access to this end-point."
        "404":
          content:
            application/json:
              examples:
                "404":
                  summary: An example of a 404 response object
                  value:
                    detailCode: 404 Not found
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server did not find a current representation for the
                        target resource.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Not Found - returned if the request URL refers to a resource
            or object that does not exist
      summary: Unsubscribe a recipient from scheduled search
      tags:
      - Scheduled Search
components:
  parameters:
    offset:
      description: |-
        Offset into the full result set. Usually specified with *limit* to paginate through the results.
        See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
      example: 0
      explode: true
      in: query
      name: offset
      required: false
      schema:
        default: 0
        format: int32
        minimum: 0
        type: integer
      style: form
    limit:
      description: |-
        Max number of results to return.
        See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
      example: 250
      explode: true
      in: query
      name: limit
      required: false
      schema:
        default: 250
        format: int32
        maximum: 250
        minimum: 0
        type: integer
      style: form
    count:
      description: |-
        If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.

        Since requesting a total count can have a performance impact, it is recommended not to send **count=true** if that value will not be used.

        See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
      example: true
      explode: true
      in: query
      name: count
      required: false
      schema:
        default: false
        type: boolean
      style: form
    id:
      description: ID of the requested document.
      example: 2c91808568c529c60168cca6f90c1313
      explode: false
      in: path
      name: id
      required: true
      schema:
        type: string
      style: simple
      x-sailpoint-resource-operation-id:
      - listAccessProfiles
      - listAccountActivities
      - listEntitlements
      - listRoles
      - listIdentities
  responses:
    "400":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorresponsedto'
      description: Client Error - Returned if the request body is invalid.
    "401":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/listScheduledSearchV1_401_response'
      description: "Unauthorized - Returned if there is no authorization header, or\
        \ if the JWT token is expired."
    "403":
      content:
        application/json:
          examples:
            "403":
              summary: An example of a 403 response object
              value:
                detailCode: 403 Forbidden
                trackingId: b21b1f7ce4da4d639f2c62a57171b427
                messages:
                - locale: en-US
                  localeOrigin: DEFAULT
                  text: The server understood the request but refuses to authorize
                    it.
          schema:
            $ref: '#/components/schemas/errorresponsedto'
      description: "Forbidden - Returned if the user you are running as, doesn't have\
        \ access to this end-point."
    "404":
      content:
        application/json:
          examples:
            "404":
              summary: An example of a 404 response object
              value:
                detailCode: 404 Not found
                trackingId: b21b1f7ce4da4d639f2c62a57171b427
                messages:
                - locale: en-US
                  localeOrigin: DEFAULT
                  text: The server did not find a current representation for the target
                    resource.
          schema:
            $ref: '#/components/schemas/errorresponsedto'
      description: Not Found - returned if the request URL refers to a resource or
        object that does not exist
    "429":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/listScheduledSearchV1_429_response'
      description: Too Many Requests - Returned in response to too many requests in
        a given period of time - rate limited. The Retry-After header in the response
        includes how long to wait before trying again.
    "500":
      content:
        application/json:
          examples:
            "500":
              summary: An example of a 500 response object
              value:
                detailCode: 500.0 Internal Fault
                trackingId: b21b1f7ce4da4d639f2c62a57171b427
                messages:
                - locale: en-US
                  localeOrigin: DEFAULT
                  text: An internal fault occurred.
          schema:
            $ref: '#/components/schemas/errorresponsedto'
      description: Internal Server Error - Returned if there is an unexpected error.
  schemas:
    scheduledsearchname:
      properties:
        name:
          description: |
            The name of the scheduled search.
          example: Daily disabled accounts
          nullable: true
          type: string
        description:
          description: |
            The description of the scheduled search.
          example: Daily disabled accounts
          nullable: true
          type: string
      type: object
    datetime:
      description: A date-time in ISO-8601 format
      example: 2018-06-25T20:22:28.104Z
      format: date-time
      nullable: true
      type: string
    scheduletype:
      description: |
        Enum representing the currently supported schedule types.

        Additional values may be added in the future without notice.
      enum:
      - DAILY
      - WEEKLY
      - MONTHLY
      - CALENDAR
      - ANNUALLY
      example: WEEKLY
      type: string
    selectortype:
      description: |
        Enum representing the currently supported selector types.

        LIST - the *values* array contains one or more distinct values.

        RANGE - the *values* array contains two values: the start and end of the range, inclusive.

        Additional values may be added in the future without notice.
      enum:
      - LIST
      - RANGE
      example: LIST
      type: string
    selector:
      properties:
        type:
          $ref: '#/components/schemas/selectortype'
        values:
          description: |
            The selected values.
          example:
          - MON
          - WED
          items:
            type: string
          type: array
        interval:
          description: |
            The selected interval for RANGE selectors.
          example: 3
          format: int32
          nullable: true
          type: integer
      required:
      - type
      - values
      type: object
    schedule:
      description: The schedule information.
      example:
        hours:
          values:
          - MON
          - WED
          interval: 3
          type: LIST
        months:
          values:
          - MON
          - WED
          interval: 3
          type: LIST
        timeZoneId: America/Chicago
        days:
          values:
          - MON
          - WED
          interval: 3
          type: LIST
        expiration: 2018-06-25T20:22:28.104Z
        type: WEEKLY
      properties:
        type:
          $ref: '#/components/schemas/scheduletype'
        months:
          $ref: '#/components/schemas/schedule_months'
        days:
          $ref: '#/components/schemas/schedule_days'
        hours:
          $ref: '#/components/schemas/schedule_hours'
        expiration:
          description: A date-time in ISO-8601 format
          example: 2018-06-25T20:22:28.104Z
          format: date-time
          nullable: true
          type: string
        timeZoneId:
          description: "The canonical TZ identifier the schedule will run in (ex.\
            \ America/New_York).  If no timezone is specified, the org's default timezone\
            \ is used."
          example: America/Chicago
          nullable: true
          type: string
      required:
      - hours
      - type
      type: object
    searchschedule:
      properties:
        savedSearchId:
          description: The ID of the saved search that will be executed.
          example: 554f1511-f0a1-4744-ab14-599514d3e57c
          type: string
        created:
          allOf:
          - $ref: '#/components/schemas/datetime'
          description: The date the scheduled search was initially created.
          readOnly: true
        modified:
          allOf:
          - $ref: '#/components/schemas/datetime'
          description: The last date the scheduled search was modified.
          readOnly: true
        schedule:
          $ref: '#/components/schemas/schedule'
        recipients:
          description: A list of identities that should receive the scheduled search
            report via email.
          items:
            $ref: '#/components/schemas/searchschedule_recipients_inner'
          type: array
        enabled:
          default: false
          description: |
            Indicates if the scheduled search is enabled.
          example: false
          type: boolean
        emailEmptyResults:
          default: false
          description: |
            Indicates if email generation should occur when search returns no results.
          example: false
          type: boolean
        displayQueryDetails:
          default: false
          description: |
            Indicates if the generated email should include the query and search results preview (which could include PII).
          example: false
          type: boolean
      required:
      - recipients
      - savedSearchId
      - schedule
      type: object
    scheduledsearch:
      allOf:
      - properties:
          id:
            description: The scheduled search ID.
            example: 0de46054-fe90-434a-b84e-c6b3359d0c64
            readOnly: true
            type: string
          owner:
            $ref: '#/components/schemas/scheduledsearch_allOf_owner'
          ownerId:
            deprecated: true
            description: |
              The ID of the scheduled search owner.

              Please use the `id` in the `owner` object instead.
            example: 2c9180867624cbd7017642d8c8c81f67
            readOnly: true
            type: string
        type: object
      - $ref: '#/components/schemas/scheduledsearchname'
      - $ref: '#/components/schemas/searchschedule'
      example:
        owner:
          id: 2c9180867624cbd7017642d8c8c81f67
          type: IDENTITY
        displayQueryDetails: false
        created: ""
        description: Daily disabled accounts
        ownerId: 2c9180867624cbd7017642d8c8c81f67
        enabled: false
        schedule:
          hours:
            values:
            - MON
            - WED
            interval: 3
            type: LIST
          months:
            values:
            - MON
            - WED
            interval: 3
            type: LIST
          timeZoneId: America/Chicago
          days:
            values:
            - MON
            - WED
            interval: 3
            type: LIST
          expiration: 2018-06-25T20:22:28.104Z
          type: WEEKLY
        recipients:
        - id: 2c9180867624cbd7017642d8c8c81f67
          type: IDENTITY
        - id: 2c9180867624cbd7017642d8c8c81f67
          type: IDENTITY
        savedSearchId: 554f1511-f0a1-4744-ab14-599514d3e57c
        name: Daily disabled accounts
        modified: ""
        id: 0de46054-fe90-434a-b84e-c6b3359d0c64
        emailEmptyResults: false
      required:
      - id
      - owner
      - ownerId
      type: object
    localeorigin:
      description: "An indicator of how the locale was selected. *DEFAULT* means the\
        \ locale is the system default. *REQUEST* means the locale was selected from\
        \ the request context (i.e., best match based on the *Accept-Language* header).\
        \ Additional values may be added in the future without notice."
      enum:
      - DEFAULT
      - REQUEST
      - null
      example: DEFAULT
      nullable: true
      type: string
    errormessagedto:
      example:
        localeOrigin: DEFAULT
        text: The request was syntactically correct but its content is semantically
          invalid.
        locale: en-US
      properties:
        locale:
          description: "The locale for the message text, a BCP 47 language tag."
          example: en-US
          nullable: true
          type: string
        localeOrigin:
          $ref: '#/components/schemas/localeorigin'
        text:
          description: Actual text of the error message in the indicated locale.
          example: The request was syntactically correct but its content is semantically
            invalid.
          type: string
      title: Error Message Dto
      type: object
    errorresponsedto:
      example:
        causes:
        - localeOrigin: DEFAULT
          text: The request was syntactically correct but its content is semantically
            invalid.
          locale: en-US
        - localeOrigin: DEFAULT
          text: The request was syntactically correct but its content is semantically
            invalid.
          locale: en-US
        messages:
        - localeOrigin: DEFAULT
          text: The request was syntactically correct but its content is semantically
            invalid.
          locale: en-US
        - localeOrigin: DEFAULT
          text: The request was syntactically correct but its content is semantically
            invalid.
          locale: en-US
        detailCode: 400.1 Bad Request Content
        trackingId: e7eab60924f64aa284175b9fa3309599
      properties:
        detailCode:
          description: Fine-grained error code providing more detail of the error.
          example: 400.1 Bad Request Content
          type: string
        trackingId:
          description: Unique tracking id for the error.
          example: e7eab60924f64aa284175b9fa3309599
          type: string
        messages:
          description: Generic localized reason for error
          items:
            $ref: '#/components/schemas/errormessagedto'
          type: array
        causes:
          description: Plain-text descriptive reasons to provide additional detail
            to the text provided in the messages field
          items:
            $ref: '#/components/schemas/errormessagedto'
          type: array
      title: Error Response Dto
      type: object
    dtotype:
      description: An enumeration of the types of DTOs supported within the IdentityNow
        infrastructure.
      enum:
      - ACCOUNT_CORRELATION_CONFIG
      - ACCESS_PROFILE
      - ACCESS_REQUEST_APPROVAL
      - ACCOUNT
      - APPLICATION
      - CAMPAIGN
      - CAMPAIGN_FILTER
      - CERTIFICATION
      - CLUSTER
      - CONNECTOR_SCHEMA
      - ENTITLEMENT
      - GOVERNANCE_GROUP
      - IDENTITY
      - IDENTITY_PROFILE
      - IDENTITY_REQUEST
      - MACHINE_IDENTITY
      - LIFECYCLE_STATE
      - PASSWORD_POLICY
      - ROLE
      - RULE
      - SOD_POLICY
      - SOURCE
      - TAG
      - TAG_CATEGORY
      - TASK_RESULT
      - REPORT_RESULT
      - SOD_VIOLATION
      - ACCOUNT_ACTIVITY
      - WORKGROUP
      example: IDENTITY
      type: string
    typedreference:
      description: |
        A typed reference to the object.
      properties:
        type:
          $ref: '#/components/schemas/dtotype'
        id:
          description: |
            The id of the object.
          example: 2c91808568c529c60168cca6f90c1313
          type: string
      required:
      - id
      - type
      type: object
    listScheduledSearchV1_401_response:
      example:
        error: "JWT validation failed: JWT is expired"
      properties:
        error:
          description: A message describing the error
          example: "JWT validation failed: JWT is expired"
      type: object
    listScheduledSearchV1_429_response:
      example:
        message: ' Rate Limit Exceeded '
      properties:
        message:
          description: A message describing the error
          example: ' Rate Limit Exceeded '
      type: object
    createScheduledSearchV1_request:
      allOf:
      - $ref: '#/components/schemas/scheduledsearchname'
      - $ref: '#/components/schemas/searchschedule'
    schedule_months:
      allOf:
      - $ref: '#/components/schemas/selector'
      - description: |
          The months to execute the search. This only applies to schedules with a type of `ANNUALLY`.
        example:
          type: LIST
          values:
          - "3"
          - "6"
          - "9"
          - "12"
        nullable: true
      example:
        values:
        - MON
        - WED
        interval: 3
        type: LIST
    schedule_days:
      allOf:
      - $ref: '#/components/schemas/selector'
      - description: |
          The days to execute the search.

          If `type` is `WEEKLY`, the values will be `MON`, `TUE`, `WED`, `THU`, `FRI`, `SAT`, and `SUN`.

          If `type` is `MONTHLY` or `ANNUALLY`, the values will be a number in double quotes, like `"1"`, `"10"`, or `"28"`.  Optionally, the value `"L"` can be used to refer to the last day of the month.
        example:
          type: LIST
          values:
          - MON
          - WED
          - FRI
        nullable: true
      example:
        values:
        - MON
        - WED
        interval: 3
        type: LIST
    schedule_hours:
      allOf:
      - $ref: '#/components/schemas/selector'
      - description: The hours selected.
        example:
          type: RANGE
          values:
          - "9"
          - "18"
          interval: 3
      example:
        values:
        - MON
        - WED
        interval: 3
        type: LIST
    searchschedule_recipients_inner:
      example:
        id: 2c9180867624cbd7017642d8c8c81f67
        type: IDENTITY
      properties:
        type:
          description: The type of object being referenced
          enum:
          - IDENTITY
          example: IDENTITY
          type: string
        id:
          description: The ID of the referenced object
          example: 2c9180867624cbd7017642d8c8c81f67
          type: string
      required:
      - id
      - type
      type: object
    scheduledsearch_allOf_owner:
      description: The owner of the scheduled search
      example:
        id: 2c9180867624cbd7017642d8c8c81f67
        type: IDENTITY
      properties:
        type:
          description: The type of object being referenced
          enum:
          - IDENTITY
          example: IDENTITY
          type: string
        id:
          description: The ID of the referenced object
          example: 2c9180867624cbd7017642d8c8c81f67
          type: string
      readOnly: true
      required:
      - id
      - type
      type: object
