openapi: 3.0.1
info:
  contact:
    name: Developer Relations
    url: https://developer.sailpoint.com/discuss/api-help
  description: "Use these APIs to interact with the Identity Security Cloud platform\
    \ to achieve repeatable, automated processes with greater scalability. We encourage\
    \ you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss\
    \ to connect with other developers using our APIs."
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://developer.sailpoint.com/discuss/tos
  title: Identity Security Cloud API - Account Deletion Requests
  version: v1
servers:
- description: This is the production API server.
  url: "https://{tenant}.api.identitynow.com"
  variables:
    tenant:
      default: sailpoint
      description: "This is the name of your tenant, typically your company's name."
- description: This is the versioned API server.
  url: "https://{apiUrl}"
  variables:
    apiUrl:
      default: sailpoint.api.identitynow.com
      description: This is the api url of your tenant
security:
- userAuth:
  - sp:scopes:all
tags:
- name: Account Deletion Requests
paths:
  /account-requests/v1/deletion:
    get:
      description: "Retrieves a paginated list of account deletion requests filtered\
        \ by the provided query parameters. When the \"mine\" parameter is set to\
        \ true, the response includes only those deletion requests that were initiated\
        \ by the currently authenticated user. If \"mine\" is false or not specified,\
        \ the endpoint returns all account deletion requests associated with the current\
        \ tenant, regardless of the initiator. This allows both users and administrators\
        \ to view relevant deletion requests based on their access level and intent."
      operationId: getAccountDeletionRequestsV1
      parameters:
      - description: |-
          Max number of results to return.
          See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
        example: 250
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 250
          format: int32
          maximum: 250
          minimum: 0
          type: integer
        style: form
      - description: |-
          Offset into the full result set. Usually specified with *limit* to paginate through the results.
          See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
        example: 0
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          format: int32
          minimum: 0
          type: integer
        style: form
      - description: |-
          If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.

          Since requesting a total count can have a performance impact, it is recommended not to send **count=true** if that value will not be used.

          See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
        example: true
        explode: true
        in: query
        name: count
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - description: "Determines whether to return only the account deletion requests\
          \ initiated by the currently authenticated user. If set to true, the response\
          \ includes only deletion requests created by the logged-in user. If set\
          \ to false or not provided, the response includes all deletion requests\
          \ for the tenant, regardless of the initiator. This parameter allows users\
          \ to view their own requests, while administrators can view all requests\
          \ within the tenant."
        example: true
        explode: true
        in: query
        name: mine
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              example:
              - accountRequestId: 18104e7e499b4e23882d6323344ab6bc
                requestType: DELETE_ACCOUNT
                createdAt: 2026-01-14T08:08:27.195Z
                completedAt: 2026-01-14T08:38:45.932Z
                overallStatus: SUCCESS
                requester:
                  type: IDENTITY
                  id: 85131bd73fdc423599e57f40b29f01fe
                  name: SailPoint Support
                requesterComments: Delete Machine Account with subtype and account
                  owner Happy Path Test#1
                accountDetails:
                  accountId: 4542bb255921482fb36f6a5550e23a99
                  accountName: "machine102,"
                  accountNativeIdentity: "CN=machine 102,OU=megapod-useast1-vivek-e2e,OU=org-data-service,DC=TestAutomationAD,DC=local"
                  accountUuid: bcde4ff4-087a-4af4-b5e4-95c85e386276
                  accountType: MACHINE
                  accountSubtypeId: d7ae9ea3-507f-4d00-9d4f-b4464b344b88
                  accountSubtype: null
                  description: null
                  sourceId: a03caa629a624cee90f94048252034cf
                  sourceName: Active Directory
                  hasEntitlements: false
                  disabled: false
                  locked: false
                  ownerIdentity:
                    type: IDENTITY
                    id: 28ca01acdd3648b4b0890ab2e0af8839
                    name: walter.white
                correlatedIdentity:
                  id: c2353ef10dd54a8e9725beff360c0be2
                  name: machine102
                  status: null
                  email: machine.102@testmail.identitysoon.com
                managerReference:
                  id: 117e169acf21f4ae28e8a06198ce7f69
                  name: manager
                  email: manager@testmail.identitysoon.com
                  status: ACTIVE
                approvalRequestId: 90a7b947-578b-4285-98dc-5d5d01c7b736
                accountRequestPhases:
                - name: APPROVAL_PHASE
                  state: APPROVED
                  started: 2026-01-14T08:08:28.644090559Z
                  finished: 2026-01-14T08:38:42.707043142Z
                - name: PROVISIONING_PHASE
                  state: PASSED
                  started: 2026-01-14T08:38:42.785577841Z
                  finished: 2026-01-14T08:38:45.932606296Z
                approvalDetails:
                  approverType: SOURCE_OWNER
                  approver:
                    id: 85131bd73fdc423599e57f40b29f01fe
                    type: IDENTITY
                    name: SailPoint Support
                  actionedBy:
                    id: 85131bd73fdc423599e57f40b29f01fe
                    type: IDENTITY
                    name: SailPoint Support
                  comments: Yes this can be deleted.
                  decisionDate: 2026-01-14T08:38:41.733779Z
                  serialOrder: 1
                  status: APPROVED
                errorDetails: null
              schema:
                items:
                  $ref: '#/components/schemas/accountactionrequestdto'
                type: array
          description: Account Action Request objects.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Client Error - Returned if the request body is invalid.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAccountDeletionRequestsV1_401_response'
          description: "Unauthorized - Returned if there is no authorization header,\
            \ or if the JWT token is expired."
        "403":
          content:
            application/json:
              examples:
                "403":
                  summary: An example of a 403 response object
                  value:
                    detailCode: 403 Forbidden
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server understood the request but refuses to authorize
                        it.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: "Forbidden - Returned if the user you are running as, doesn't\
            \ have access to this end-point."
        "404":
          content:
            application/json:
              examples:
                "404":
                  summary: An example of a 404 response object
                  value:
                    detailCode: 404 Not found
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server did not find a current representation for the
                        target resource.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Not Found - returned if the request URL refers to a resource
            or object that does not exist
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAccountDeletionRequestsV1_429_response'
          description: Too Many Requests - Returned in response to too many requests
            in a given period of time - rate limited. The Retry-After header in the
            response includes how long to wait before trying again.
        "500":
          content:
            application/json:
              examples:
                "500":
                  summary: An example of a 500 response object
                  value:
                    detailCode: 500.0 Internal Fault
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: An internal fault occurred.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Internal Server Error - Returned if there is an unexpected
            error.
      security:
      - userAuth:
        - idn:account-requests:read
        - idn:account-requests:management
      summary: List of Account Deletion Requests
      tags:
      - Account Deletion Requests
      x-sailpoint-userLevels:
      - ORG_ADMIN
      - SOURCE_ADMIN
      - SOURCE_SUBADMIN
      - USER
  /account-requests/v1/account/{accountId}/delete:
    post:
      description: "Initiates an account deletion request for the specified account.\n\
        This method validates the input data, processes the deletion request,\nand\
        \ generates an asynchronous result containing a tracking ID. \n>**NOTE: You\
        \ can only delete accounts from sources of the \"Connected\" type. which supports\
        \ account deletion**"
      operationId: deleteAccountRequestV1
      parameters:
      - description: Account ID.
        example: ef38f94347e94562b5bb8424a56498d8
        explode: false
        in: path
        name: accountId
        required: true
        schema:
          type: string
        style: simple
        x-sailpoint-resource-operation-id: listAccountsV1
      requestBody:
        content:
          application/json:
            example:
              comments: I requested this account deletion.
            schema:
              $ref: '#/components/schemas/accountdeleterequestinput'
        required: false
      responses:
        "202":
          content:
            application/json:
              example:
                accountRequestId: 2d81808474683da6017468693c260196
              schema:
                $ref: '#/components/schemas/accountrequestasyncresult'
          description: Account deletion request details.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Client Error - Returned if the request body is invalid.
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAccountDeletionRequestsV1_401_response'
          description: "Unauthorized - Returned if there is no authorization header,\
            \ or if the JWT token is expired."
        "403":
          content:
            application/json:
              examples:
                "403":
                  summary: An example of a 403 response object
                  value:
                    detailCode: 403 Forbidden
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server understood the request but refuses to authorize
                        it.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: "Forbidden - Returned if the user you are running as, doesn't\
            \ have access to this end-point."
        "404":
          content:
            application/json:
              examples:
                "404":
                  summary: An example of a 404 response object
                  value:
                    detailCode: 404 Not found
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: The server did not find a current representation for the
                        target resource.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Not Found - returned if the request URL refers to a resource
            or object that does not exist
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAccountDeletionRequestsV1_429_response'
          description: Too Many Requests - Returned in response to too many requests
            in a given period of time - rate limited. The Retry-After header in the
            response includes how long to wait before trying again.
        "500":
          content:
            application/json:
              examples:
                "500":
                  summary: An example of a 500 response object
                  value:
                    detailCode: 500.0 Internal Fault
                    trackingId: b21b1f7ce4da4d639f2c62a57171b427
                    messages:
                    - locale: en-US
                      localeOrigin: DEFAULT
                      text: An internal fault occurred.
              schema:
                $ref: '#/components/schemas/errorresponsedto'
          description: Internal Server Error - Returned if there is an unexpected
            error.
      security:
      - userAuth:
        - idn:account-requests:create
      summary: Delete account
      tags:
      - Account Deletion Requests
      x-sailpoint-userLevels:
      - ORG_ADMIN
      - SOURCE_ADMIN
      - SOURCE_SUBADMIN
      - USER
components:
  parameters:
    limit:
      description: |-
        Max number of results to return.
        See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
      example: 250
      explode: true
      in: query
      name: limit
      required: false
      schema:
        default: 250
        format: int32
        maximum: 250
        minimum: 0
        type: integer
      style: form
    offset:
      description: |-
        Offset into the full result set. Usually specified with *limit* to paginate through the results.
        See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
      example: 0
      explode: true
      in: query
      name: offset
      required: false
      schema:
        default: 0
        format: int32
        minimum: 0
        type: integer
      style: form
    count:
      description: |-
        If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.

        Since requesting a total count can have a performance impact, it is recommended not to send **count=true** if that value will not be used.

        See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
      example: true
      explode: true
      in: query
      name: count
      required: false
      schema:
        default: false
        type: boolean
      style: form
  responses:
    "400":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorresponsedto'
      description: Client Error - Returned if the request body is invalid.
    "401":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/getAccountDeletionRequestsV1_401_response'
      description: "Unauthorized - Returned if there is no authorization header, or\
        \ if the JWT token is expired."
    "403":
      content:
        application/json:
          examples:
            "403":
              summary: An example of a 403 response object
              value:
                detailCode: 403 Forbidden
                trackingId: b21b1f7ce4da4d639f2c62a57171b427
                messages:
                - locale: en-US
                  localeOrigin: DEFAULT
                  text: The server understood the request but refuses to authorize
                    it.
          schema:
            $ref: '#/components/schemas/errorresponsedto'
      description: "Forbidden - Returned if the user you are running as, doesn't have\
        \ access to this end-point."
    "404":
      content:
        application/json:
          examples:
            "404":
              summary: An example of a 404 response object
              value:
                detailCode: 404 Not found
                trackingId: b21b1f7ce4da4d639f2c62a57171b427
                messages:
                - locale: en-US
                  localeOrigin: DEFAULT
                  text: The server did not find a current representation for the target
                    resource.
          schema:
            $ref: '#/components/schemas/errorresponsedto'
      description: Not Found - returned if the request URL refers to a resource or
        object that does not exist
    "429":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/getAccountDeletionRequestsV1_429_response'
      description: Too Many Requests - Returned in response to too many requests in
        a given period of time - rate limited. The Retry-After header in the response
        includes how long to wait before trying again.
    "500":
      content:
        application/json:
          examples:
            "500":
              summary: An example of a 500 response object
              value:
                detailCode: 500.0 Internal Fault
                trackingId: b21b1f7ce4da4d639f2c62a57171b427
                messages:
                - locale: en-US
                  localeOrigin: DEFAULT
                  text: An internal fault occurred.
          schema:
            $ref: '#/components/schemas/errorresponsedto'
      description: Internal Server Error - Returned if there is an unexpected error.
  schemas:
    dtotype:
      description: An enumeration of the types of DTOs supported within the IdentityNow
        infrastructure.
      enum:
      - ACCOUNT_CORRELATION_CONFIG
      - ACCESS_PROFILE
      - ACCESS_REQUEST_APPROVAL
      - ACCOUNT
      - APPLICATION
      - CAMPAIGN
      - CAMPAIGN_FILTER
      - CERTIFICATION
      - CLUSTER
      - CONNECTOR_SCHEMA
      - ENTITLEMENT
      - GOVERNANCE_GROUP
      - IDENTITY
      - IDENTITY_PROFILE
      - IDENTITY_REQUEST
      - MACHINE_IDENTITY
      - LIFECYCLE_STATE
      - PASSWORD_POLICY
      - ROLE
      - RULE
      - SOD_POLICY
      - SOURCE
      - TAG
      - TAG_CATEGORY
      - TASK_RESULT
      - REPORT_RESULT
      - SOD_VIOLATION
      - ACCOUNT_ACTIVITY
      - WORKGROUP
      example: IDENTITY
      type: string
    basereferencedto:
      properties:
        type:
          $ref: '#/components/schemas/dtotype'
        id:
          description: ID of the object to which this reference applies
          example: 2c91808568c529c60168cca6f90c1313
          type: string
        name:
          description: Human-readable display name of the object to which this reference
            applies
          example: William Wilson
          type: string
      title: Base Reference Dto
      type: object
    accountdetails:
      description: Account Details
      properties:
        id:
          description: unique id of this object
          example: 2c91808474683da6017468693c260195
          type: string
        name:
          type: string
        accountId:
          example: 4191808474683da6017468693c260195
          type: string
        description:
          type: string
        nativeIdentity:
          type: string
        uuid:
          type: string
        displayName:
          type: string
        disabled:
          type: boolean
        locked:
          type: boolean
        uncorrelated:
          type: boolean
        systemAccount:
          type: boolean
        authoritative:
          type: boolean
        supportsPasswordChange:
          type: boolean
        attributes:
          type: object
        application:
          type: object
        identity:
          type: object
        schema:
          type: object
        pendingAccessRequestIds:
          items:
            type: string
          type: array
        features:
          items:
            enum:
            - AUTHENTICATE
            - COMPOSITE
            - DIRECT_PERMISSIONS
            - DISCOVER_SCHEMA
            - ENABLE
            - MANAGER_LOOKUP
            - NO_RANDOM_ACCESS
            - PROXY
            - SEARCH
            - TEMPLATE
            - UNLOCK
            - UNSTRUCTURED_TARGETS
            - SHAREPOINT_TARGET
            - PROVISIONING
            - GROUP_PROVISIONING
            - SYNC_PROVISIONING
            - PASSWORD
            - CURRENT_PASSWORD
            - ACCOUNT_ONLY_REQUEST
            - ADDITIONAL_ACCOUNT_REQUEST
            - NO_AGGREGATION
            - GROUPS_HAVE_MEMBERS
            - NO_PERMISSIONS_PROVISIONING
            - NO_GROUP_PERMISSIONS_PROVISIONING
            - NO_UNSTRUCTURED_TARGETS_PROVISIONING
            - NO_DIRECT_PERMISSIONS_PROVISIONING
            type: string
          type: array
        meta:
          type: object
      title: Account Details
      type: object
    identityreference:
      description: The manager for the identity.
      nullable: true
      properties:
        type:
          $ref: '#/components/schemas/dtotype'
        id:
          description: Identity id
          example: 2c9180a46faadee4016fb4e018c20639
          type: string
        name:
          description: Human-readable display name of identity.
          example: Thomas Edison
          type: string
      title: Identity Reference
      type: object
    accountrequestphasestate:
      description: "The current phase state of the account request, indicating its\
        \ progress or outcome in the approval workflow."
      enum:
      - PENDING
      - CANCELLED
      - APPROVED
      - REJECTED
      - PASSED
      - FAILED
      - NOT_STARTED
      example: APPROVED
      type: string
    accountrequestphase:
      description: "Contains detailed information about each phase in the account\
        \ request process, including its type, current state, and relevant timestamps."
      properties:
        name:
          description: Enum of account request phase type
          enum:
          - APPROVAL_PHASE
          - PROVISIONING_PHASE
          example: APPROVAL_PHASE
          title: AccountRequestPhaseType
          type: string
        state:
          $ref: '#/components/schemas/accountrequestphasestate'
        started:
          description: Start date of account request phase.
          example: 2026-01-21T11:43:22.432Z
          format: date-time
          readOnly: true
          type: string
        finished:
          description: Finish date of account request phase.
          example: 2026-01-21T11:45:22.432Z
          format: date-time
          readOnly: true
          type: string
      title: Account Request phase
      type: object
    approverreference:
      properties:
        id:
          description: "Id of supported DtoType like IDENTITY, MACHINE_IDENTITY etc."
          example: 85131bd73fdc423599e57f40b29f01fe
          type: string
        type:
          description: Type of Dto
          example: IDENTITY
          type: string
        name:
          description: "Display name of DtoType like IDENTITY, MACHINE_IDENTITY etc"
          example: SailPoint Support
          type: string
      title: ApproverReference
      type: object
    approverdto:
      description: "Contains detailed information about the approver, including their\
        \ identity, contact details, type, and references to related identities such\
        \ as owners, actioned identities, and members."
      properties:
        identityID:
          description: Identity ID and it cannot be null.
          example: 22efd140d88a4ceeab32c8829973244c
          nullable: false
          type: string
        id:
          description: Optional id
          nullable: true
          type: string
        name:
          description: Identity display name
          example: SailPoint Support
          type: string
        email:
          description: Email address of identity
          example: support@testmail.identitysoon.com
          type: string
        type:
          description: Used to mention type of data transfer object in this case it
            is used to transfer IDENTITY data.
          example: IDENTITY
          type: string
        ownerOf:
          description: List of reference of identity type dto for account owner identities
          items:
            $ref: '#/components/schemas/approverreference'
          nullable: true
          type: array
        actionedAs:
          description: List of reference of identity type dto who acted on behalf
            of other identities.
          items:
            $ref: '#/components/schemas/approverreference'
          nullable: true
          type: array
        members:
          description: List of reference of identity type dto for member identities.
          items:
            $ref: '#/components/schemas/approverreference'
          nullable: true
          type: array
      title: Approver Dto
      type: object
    approvaldetails:
      description: "Contains comprehensive details about the approval process, including\
        \ the approver's information, comments, decision date, serial order, and the\
        \ current status of the approval request."
      properties:
        approver:
          $ref: '#/components/schemas/approverdto'
        approverComments:
          description: Comments added by approver while rejecting or approving the
            account deletion request.
          example: Approving account deletion request due to long term inactivity
            of account.
          type: string
        decisionDate:
          description: Decision date of approval rejected or approved.
          example: 2026-01-21T11:43:22.432Z
          format: date-time
          readOnly: true
          type: string
        serialOrder:
          description: SerialOrder of approval details.
          example: 12345
          format: int64
          type: integer
        status:
          $ref: '#/components/schemas/accountrequestphasestate'
      title: Approval Details
      type: object
    accountactionrequestdto:
      description: "Represents a request to perform an action on an account, such\
        \ as deletion or modification."
      example:
        requester:
          name: William Wilson
          id: 2c91808568c529c60168cca6f90c1313
          type: IDENTITY
        accountRequestId: 2d8180a46faadee4016fb4e018c20648
        completedAt: 2026-01-20T21:35:00Z
        approvalDetails:
        - identityID: 85131bd73fdc423599e57f40b29f01fe
          id: 85131bd73fdc423599e57f40b29f01fe
          name: SailPoint Support
          email: support@testmail.identitysoon.com
          type: IDENTITY
          ownerOf:
            email: Alfred.255e71dfc6e@testmail.identitysoon.com
            type: IDENTITY
            id: 7ec252acbd4245548bc25df22348cb75
            name: Alfred
          actionedAs:
            email: Alfred.255e71dfc6e@testmail.identitysoon.com
            type: IDENTITY
            id: 7ec252acbd4245548bc25df22348cb75
            name: Alfred
          members:
            email: Alfred.255e71dfc6e@testmail.identitysoon.com
            type: IDENTITY
            id: 7ec252acbd4245548bc25df22348cb75
            name: Alfred
        requestType: 2c7180a46faadee4016fb4e018c20648
        correlatedIdentity:
          id: c2353ef10dd54a8e9725beff360c0be2
          name: machine102
          email: machine.102@testmail.identitysoon.com
          status: ACTIVE
        createdAt: 2026-01-20T21:30:00Z
        approvalRequestId: 06cc946d58bb4422bbd094cf78667d42
        accountRequestPhases:
        - name: APPROVAL_PHASE
          state: APPROVED
          started: 2026-01-14T08:08:28.644090559Z
          finished: 2026-01-14T08:38:42.707043142Z
        - name: PROVISIONING_PHASE
          state: PASSED
          started: 2026-01-14T08:38:42.785577841Z
          finished: 2026-01-14T08:38:45.932606296Z
        accountDetails:
          schema: "{}"
          authoritative: true
          displayName: displayName
          description: description
          uuid: uuid
          nativeIdentity: nativeIdentity
          supportsPasswordChange: true
          accountId: 4191808474683da6017468693c260195
          features:
          - AUTHENTICATE
          - AUTHENTICATE
          uncorrelated: true
          application: "{}"
          identity: "{}"
          meta: "{}"
          name: name
          disabled: true
          attributes: "{}"
          id: 2c91808474683da6017468693c260195
          locked: true
          systemAccount: true
          pendingAccessRequestIds:
          - pendingAccessRequestIds
          - pendingAccessRequestIds
        managerReference:
          id: 117e169acf21f4ae28e8a06198ce7f69
          name: manager
          email: manager@testmail.identitysoon.com
          status: ACTIVE
        requesterComments: User requested account deletion due to inactivity.
        overallStatus: SUCCESS
        errorDetails: Detailed error message.
      properties:
        accountRequestId:
          description: Account requester ID.
          example: 2d8180a46faadee4016fb4e018c20648
          type: string
        requestType:
          description: Access item requester's identity ID.
          example: 2c7180a46faadee4016fb4e018c20648
          type: string
        createdAt:
          description: Creation date and time of account deletion request date.
          example: 2026-01-20T21:30:00Z
          format: date-time
          readOnly: true
          type: string
        completedAt:
          description: Account deletion request completion date and time.
          example: 2026-01-20T21:35:00Z
          format: date-time
          readOnly: true
          type: string
        overallStatus:
          description: Overall status of deletion request.
          example: SUCCESS
          type: string
        requester:
          $ref: '#/components/schemas/accountactionrequestdto_requester'
        requesterComments:
          description: Comments added by the requester while creating the account
            deletion request.
          example: User requested account deletion due to inactivity.
          type: string
        accountDetails:
          $ref: '#/components/schemas/accountactionrequestdto_accountDetails'
        correlatedIdentity:
          $ref: '#/components/schemas/accountactionrequestdto_correlatedIdentity'
        managerReference:
          allOf:
          - $ref: '#/components/schemas/identityreference'
          example:
            id: 117e169acf21f4ae28e8a06198ce7f69
            name: manager
            email: manager@testmail.identitysoon.com
            status: ACTIVE
        approvalRequestId:
          description: ID of the approval request associated with the account deletion
            action.
          example: 06cc946d58bb4422bbd094cf78667d42
          type: string
        accountRequestPhases:
          description: List of account request phases.
          example:
          - name: APPROVAL_PHASE
            state: APPROVED
            started: 2026-01-14T08:08:28.644090559Z
            finished: 2026-01-14T08:38:42.707043142Z
          - name: PROVISIONING_PHASE
            state: PASSED
            started: 2026-01-14T08:38:42.785577841Z
            finished: 2026-01-14T08:38:45.932606296Z
          items:
            $ref: '#/components/schemas/accountrequestphase'
          type: array
        approvalDetails:
          description: List approval details
          example:
          - identityID: 85131bd73fdc423599e57f40b29f01fe
            id: 85131bd73fdc423599e57f40b29f01fe
            name: SailPoint Support
            email: support@testmail.identitysoon.com
            type: IDENTITY
            ownerOf:
              email: Alfred.255e71dfc6e@testmail.identitysoon.com
              type: IDENTITY
              id: 7ec252acbd4245548bc25df22348cb75
              name: Alfred
            actionedAs:
              email: Alfred.255e71dfc6e@testmail.identitysoon.com
              type: IDENTITY
              id: 7ec252acbd4245548bc25df22348cb75
              name: Alfred
            members:
              email: Alfred.255e71dfc6e@testmail.identitysoon.com
              type: IDENTITY
              id: 7ec252acbd4245548bc25df22348cb75
              name: Alfred
          items:
            $ref: '#/components/schemas/approvaldetails'
          type: array
        errorDetails:
          description: Detailed error information.
          example: Detailed error message.
          nullable: true
          type: string
      title: Account Action Request Dto
      type: object
    localeorigin:
      description: "An indicator of how the locale was selected. *DEFAULT* means the\
        \ locale is the system default. *REQUEST* means the locale was selected from\
        \ the request context (i.e., best match based on the *Accept-Language* header).\
        \ Additional values may be added in the future without notice."
      enum:
      - DEFAULT
      - REQUEST
      - null
      example: DEFAULT
      nullable: true
      type: string
    errormessagedto:
      example:
        localeOrigin: DEFAULT
        text: The request was syntactically correct but its content is semantically
          invalid.
        locale: en-US
      properties:
        locale:
          description: "The locale for the message text, a BCP 47 language tag."
          example: en-US
          nullable: true
          type: string
        localeOrigin:
          $ref: '#/components/schemas/localeorigin'
        text:
          description: Actual text of the error message in the indicated locale.
          example: The request was syntactically correct but its content is semantically
            invalid.
          type: string
      title: Error Message Dto
      type: object
    errorresponsedto:
      example:
        causes:
        - localeOrigin: DEFAULT
          text: The request was syntactically correct but its content is semantically
            invalid.
          locale: en-US
        - localeOrigin: DEFAULT
          text: The request was syntactically correct but its content is semantically
            invalid.
          locale: en-US
        messages:
        - localeOrigin: DEFAULT
          text: The request was syntactically correct but its content is semantically
            invalid.
          locale: en-US
        - localeOrigin: DEFAULT
          text: The request was syntactically correct but its content is semantically
            invalid.
          locale: en-US
        detailCode: 400.1 Bad Request Content
        trackingId: e7eab60924f64aa284175b9fa3309599
      properties:
        detailCode:
          description: Fine-grained error code providing more detail of the error.
          example: 400.1 Bad Request Content
          type: string
        trackingId:
          description: Unique tracking id for the error.
          example: e7eab60924f64aa284175b9fa3309599
          type: string
        messages:
          description: Generic localized reason for error
          items:
            $ref: '#/components/schemas/errormessagedto'
          type: array
        causes:
          description: Plain-text descriptive reasons to provide additional detail
            to the text provided in the messages field
          items:
            $ref: '#/components/schemas/errormessagedto'
          type: array
      title: Error Response Dto
      type: object
    accountdeleterequestinput:
      description: "Contains the required information for processing a user-initiated\
        \ account deletion request, including the reason for deletion."
      properties:
        comments:
          description: Reason for deleting the account.
          example: Requesting account deletion request
          type: string
      title: Account Delete Request Input
      type: object
    accountrequestasyncresult:
      description: Asynchronous response containing a unique tracking ID for the account
        request
      example:
        accountRequestId: 2d81808474683da6017468693c260196
      properties:
        accountRequestId:
          description: Id of the account request
          example: 2d81808474683da6017468693c260196
          type: string
      required:
      - accountRequestId
      title: Account Create/Delete Async Result
      type: object
    getAccountDeletionRequestsV1_401_response:
      example:
        error: "JWT validation failed: JWT is expired"
      properties:
        error:
          description: A message describing the error
          example: "JWT validation failed: JWT is expired"
      type: object
    getAccountDeletionRequestsV1_429_response:
      example:
        message: ' Rate Limit Exceeded '
      properties:
        message:
          description: A message describing the error
          example: ' Rate Limit Exceeded '
      type: object
    accountactionrequestdto_requester:
      allOf:
      - $ref: '#/components/schemas/basereferencedto'
      - description: The identity who request this account delete request.
        example:
          type: IDENTITY
          id: SailPoint Support
          name: 85131bd73fdc423599e57f40b29f01fe
        nullable: false
      example:
        name: William Wilson
        id: 2c91808568c529c60168cca6f90c1313
        type: IDENTITY
    accountactionrequestdto_accountDetails:
      allOf:
      - $ref: '#/components/schemas/accountdetails'
      - description: Account Details
        example:
          accountId: 4542bb255921482fb36f6a5550e23a99
          accountName: machine102
          accountNativeIdentity: "CN=machine 102,OU=megapod-useast1-vivek-e2e,OU=org-data-service,DC=TestAutomationAD,DC=local"
          accountUuid:
            bcde4ff4-087a-4af4-b5e4-95c85e386276: null
          accountType: MACHINE
          accountSubtypeId: d7ae9ea3-507f-4d00-9d4f-b4464b344b88
          accountSubtype: null
          description: null
          sourceId: a03caa629a624cee90f94048252034cf
          sourceName: Active Directory
          hasEntitlements: false
          disabled: false
          locked: false
          ownerIdentity:
            type: IDENTITY
            id: 28ca01acdd3648b4b0890ab2e0af8839
            name: walter.white
        nullable: false
      example:
        schema: "{}"
        authoritative: true
        displayName: displayName
        description: description
        uuid: uuid
        nativeIdentity: nativeIdentity
        supportsPasswordChange: true
        accountId: 4191808474683da6017468693c260195
        features:
        - AUTHENTICATE
        - AUTHENTICATE
        uncorrelated: true
        application: "{}"
        identity: "{}"
        meta: "{}"
        name: name
        disabled: true
        attributes: "{}"
        id: 2c91808474683da6017468693c260195
        locked: true
        systemAccount: true
        pendingAccessRequestIds:
        - pendingAccessRequestIds
        - pendingAccessRequestIds
    accountactionrequestdto_correlatedIdentity:
      allOf:
      - $ref: '#/components/schemas/identityreference'
      - description: Correlated Identity details
      example:
        id: c2353ef10dd54a8e9725beff360c0be2
        name: machine102
        email: machine.102@testmail.identitysoon.com
        status: ACTIVE
